Wording Change (#1): Replace "Conforming Solution" with "Conformant Solution"
sine-fdn/pact-catalog-frontend pull request #252
Opened 2023-04-14 17:49 UTC by zeitgeist

- refactor(wording): replace "Conforming" with "Conformant" in description(s)
- refactor(code): rename data type `ConformingSolution` to `ConformantSolution`

2023-04-17 09:26 UTC, fkettelhoit requested changes
There are still a couple of occurrences of "conforming" instead of "conformant" in the code base, most notably the `<h2>` in `usage-tab.tsx` and  the `mainText` in `about.tsx`:

```
components/extension-tabs/usage-tab.tsx:  const { dependencies, conformingSolutions } = extension;
components/extension-tabs/usage-tab.tsx:        <h2>PACT Conforming Solutions</h2>
components/extension-tabs/usage-tab.tsx:          {conformingSolutions &&
components/extension-tabs/usage-tab.tsx:            conformingSolutions.map(({ id, version, name, providerName }) => {
lib/catalog-types.ts:  conformingSolutions: ConformantSolution[];
lib/data-model-extensions.ts:import { getConformingSolutions } from './solutions';
lib/data-model-extensions.ts:    conformingSolutions: getConformingSolutions(extensionJson),
lib/solutions.ts:export function getConformingSolutions(
lib/solutions.ts:  let conformingSolutions: ConformantSolution[] = [];
lib/solutions.ts:          conformingSolutions.push(solution);
lib/solutions.ts:  return conformingSolutions;
pages/about.tsx:              mainText="PACT Conforming Solutions"
```

2023-04-17 09:26 UTC, fkettelhoit commented on frontend/pages/about.tsx
> +  const REF_CONFORMANT_SOLUTIONS = 'pact-conformant-solutions';
I usually associate "ref" in a React context with the `useRef` hook, perhaps `ID_CONFORMANT_SOLUTIONS` or similar could be an alternative here?

2023-04-17 09:26 UTC, fkettelhoit commented on frontend/pages/about.tsx
> +            <a
Any reason why you decided to go with an `a` instead of a `Link`? I don't know enough about Next.js to know whether this makes a difference here (I think it shouldn't, since the router is not really involved if it's only a fragment link), just wanted to make sure this is intentional.

2023-04-17 09:26 UTC, fkettelhoit commented on frontend/components/cards.tsx
> +      return `${searchValue !== '' ? searchResults.length : 'All'} ${firstFilterValue !== '' ? `${firstFilterValue} related` : ''
Are you using different `prettier` settings than Raimundo? The PR contains quite a few changes that seem to be only whitespace reformatting, as far as I can tell.

2023-04-18 09:21 UTC, zeitgeist commented on frontend/pages/about.tsx
> +  const REF_CONFORMANT_SOLUTIONS = 'pact-conformant-solutions';
just saw there is a nice `useId()` hook and used that instead.

2023-04-18 10:25 UTC, zeitgeist commented on frontend/pages/about.tsx
> +            <a
To me seems in line with the Next.js documentation: https://nextjs.org/docs/api-reference/next/link#disable-scrolling-to-the-top-of-the-page

2023-04-18 10:25 UTC, zeitgeist commented on frontend/components/cards.tsx
> +      return `${searchValue !== '' ? searchResults.length : 'All'} ${firstFilterValue !== '' ? `${firstFilterValue} related` : ''
I am apparently. Would you share (or add to this repo) the settings you are using please?

2023-04-18 10:27 UTC, zeitgeist commented
@fkettelhoit please review again

2023-04-18 10:33 UTC, fkettelhoit commented on frontend/pages/about.tsx
> +            <a
The documentation uses `<Link>` instead of `<a>`, however? Also, according to the documentation `<Link>` adds auto-scrolling, which we don't get if we just use an `<a>`, right?

2023-04-18 10:35 UTC, fkettelhoit requested changes
There are still a couple of occurrences of "Conforming" instead of "Conformant":

```
frontend/components/extension-tabs/usage-tab.tsx:        <h2>PACT Conforming Solutions</h2>
frontend/lib/data-model-extensions.ts:    conformantSolutions: getConformingSolutions(extensionJson),
frontend/pages/about.tsx:              mainText="PACT Conforming Solutions"
```

2023-04-18 11:26 UTC, fkettelhoit approved these changes

2023-04-18 21:17 UTC, merged