Badge api
sine-fdn/pact-catalog-frontend pull request #280
Opened 2023-06-29 15:41 UTC by raimundo-henriques

Simple api dynamic route with endpoints generated by replacing `[solutionId]` and `[version]` below by the actual ID and version of a solution already in the catalog: 
```
/api/solutions/[solutionId]/[version]
```
The api checks if the solution exists. If so, it calls the plausible api for tracking purposes and returns a png. If not, returns 400 and error message.

2023-06-29 20:51 UTC, zeitgeist requested changes
The first 3 comments need to be addressed first. 

In addation, I was wondering whether this couldn't be something like a middleware which eventually internally redirects the request to the badge file?

2023-06-29 20:51 UTC, zeitgeist commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +  const endpoint = req.url?.split('solutions')[1] || '';
Please check whether `solutionId` is available via `req.query.solutionId` (i.e. from the path placeholder `[solutionId]`) such that you can skip this little "hack" here

2023-06-29 20:51 UTC, zeitgeist commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +  const validEndpoints = solutionPaths.map((path) => {
instead of iterating over all possible solutions, how about constructing a path a la `../catalog/solutions/${req.query.solutionId}/${req.query.version}/solution.json` to check whether the solution indeed exists?

2023-06-29 20:51 UTC, zeitgeist commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +    const badgePath = path.join(process.cwd(), 'public/logos/pact-logo.png');
I think it would make sense to move the badge into the catalog rather than this repo. WDYT?

2023-06-29 20:51 UTC, zeitgeist commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +        'User-Agent':
have you looked into alternative ways to access the user agent through `req` by any chance?

2023-07-03 11:17 UTC, raimundo-henriques commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +    const badgePath = path.join(process.cwd(), 'public/logos/pact-logo.png');
Since that's the repo actually owned by WBCSD, I think that's what makes the most sense, yes!
On the other hand, since SP's will see it in the repo when they push their solution, I wonder whether it will make it slightly harder to make sure they use our API. But that's just a matter of making it clear when communicating it.
As soon as the badge is ready I'll add it there and update the code here.

2023-07-03 11:19 UTC, raimundo-henriques commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +        'User-Agent':
Not yet, as it wasn't clear for me whether we actually wanted to gather this data, but I will do that right away

2023-07-03 11:20 UTC, raimundo-henriques commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +  const endpoint = req.url?.split('solutions')[1] || '';
Of course! Thank you! I'll look into it

2023-07-03 19:24 UTC, zeitgeist commented on frontend/pages/api/solutions/[solutionId]/[version].ts
> +    const badgePath = path.join(process.cwd(), 'public/logos/pact-logo.png');
This is a valid concern (i.e. companies to "circumevent" the API), but this equally applies to the API as well; i.e. they could download (from the API) once and then serve it statically. The only thing which prevents them from doing so is a contract / IP rights eventually.

2023-07-05 20:27 UTC, zeitgeist commented
@raimundo-henriques @fkettelhoit to summarize my changes, picking up from your's Raimundo:

1. refactored the tracking-related code into dedicated file / module (`lib/plausibleTracking.ts`)
2. slightly changed the badge image asset handling code; before you were using globbing and then moving 1 file; now it's all hard-coded: `$catalog/badge/conformance.svg` is copied into `public/badge/conformance.svg` for simplicity reasons. Frankly, I did not quite get why we need the flexibility with badges there so I removed it altogether. Happy to revert / skip this single change of course, @raimundo-henriques

2023-07-05 20:27 UTC, zeitgeist commented
as a follow up, I think we must add a test case as well. Would you be up for this, @raimundo-henriques ?

2023-07-05 20:28 UTC, zeitgeist approved these changes

2023-07-06 08:39 UTC, raimundo-henriques reviewed
Thank you, @zeitgeist , it's looking great!
My idea behind not hard coding the path to the badge svg was that I thought it could be good to keep the file name open, but I agree that this is unnecessary;
I'm very happy to work on a test case for this feature!
Thanks!

2023-07-06 19:53 UTC, merged